---
name: Games-Sudoku-CPSearch
version: 0.04
author:
  - 'Martin-Louis Bright <mlbright@gmail.com>'
abstract: A fast technique to solve Sudoku problems.
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Test::More: 0
provides:
  Games::Sudoku::CPSearch:
    file: lib/Games/Sudoku/CPSearch.pm
    version: 0.04
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
