---
name: Games-Sudoku-CPSearch
version: 0.10
author:
  - 'Martin-Louis Bright <mlbright@gmail.com>'
abstract: Solve Sudoku problems quickly.
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Test::More: 0
provides:
  Games::Sudoku::CPSearch:
    file: lib/Games/Sudoku/CPSearch.pm
    version: 0.10
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
